services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: [ "mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
#    restart: unless-stopped
    #使用env配置
    env_file:
      - .env
    environment:
      #要拿这个作为内网host
      - MYSQL_HOST=db
      - MYSQL_DATABASE= ${MYSQL_DATABASE}
      - MYSQL_USER= ${MYSQL_USER}
      - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
    depends_on:
      - db
    #在容器运行时挂载，覆盖镜像中的文件
    # 生产环境（不需要 volumes）
    volumes:
      - .:/backend  # 代码实时同步
    ports:
      - "80:8000"
      # 先启动再进入改
#    command: sleep infinity

volumes:
  db_data:


